Add type hints and fix *most* mypy errors for HP drivers
ktbyers/netmiko pull request #2140
Opened 2021-02-05 18:39 UTC by wrgeorge1983

needs some bugfixing because of this:
```
hp\hp_procurve.py:16: error: "HPProcurveSSHChannel" has no attribute "use_keys"
hp\hp_procurve.py:16: error: "HPProcurveSSHChannel" has no attribute "password"
```
```python
class HPProcurveSSHChannel(SSHChannel):
    def _build_ssh_client(self, no_auth=True) -> paramiko.SSHClient:
        """Allow passwordless authentication for HP devices being provisioned."""
        if not self.use_keys and not self.password:
            return super()._build_ssh_client(no_auth=no_auth)
        else:
            return super()._build_ssh_client(no_auth=False)

```

that'll come in a following commit

2021-02-05 19:08 UTC, wrgeorge1983 commented on netmiko/base_connection.py
> +        assert issubclass(ChannelClass, SSHChannel)
I *BELIEVE* this is safe and correct.  if it's not would need to either make it true, or do something else to make sure it's okay to provide `use_keys` and `password` parameters.

2021-02-10 16:55 UTC, ktbyers requested changes
I think I would probably focus on submitting the HP Compware PR and have that be stand-alone. That will make it a lot easier for me to review/merge.

The biggest missing item is type hints on the arguments for all of the functions.

2021-02-10 16:55 UTC, ktbyers commented on netmiko/hp/hp_comware.py
> +    def exit_config_mode(self, exit_config="return", pattern=r">") -> str:
Your missing the type hints on the arguments i.e. `exit_config: str = "return"` et cetera.

2021-02-10 16:55 UTC, ktbyers commented on netmiko/hp/hp_comware.py
> +    def check_config_mode(self, check_string="]", pattern: str = "]") -> bool:
Missing type hints on check_string argument.

2021-02-10 16:55 UTC, ktbyers commented on netmiko/hp/hp_comware.py
> +    ) -> str:
Should add type hints on the arguments as well.

2021-02-11 04:36 UTC, ktbyers commented
Okay, I realized after the fact that I had already done both hp_procurve and hp_comware and just hadn't pushed them up here. That is totally my bad...so sorry about that.

Looking at the mypy output the next drivers that need done are the:

```
fortinet_ssh
flexvnf_ssh
f5_tmsh_ssh
```

So if you want to work on those, let me know.

So I am going to go ahead and close this PR, and then we can start on the "f" through "a" drivers.

Once again I apologize about the wasted effort here.


Regards, Kirk

2021-02-11 04:36 UTC, closed without merging