Added support for ericsson mltn 66XX & 63XX
ktbyers/netmiko pull request #3150
Opened 2023-03-29 13:35 UTC by codekuu

Added support for Ericsson MLTN 66XX and 63XX series.

2023-04-14 11:32 UTC, codekuu commented
@ktbyers hey! Do you have time to look at this?
(you told me to ping you)

2023-04-17 02:40 UTC, ktbyers commented
@codekuu Something broke with respect to Netmiko and GitHub actions. I am looking into it.

2023-04-17 03:01 UTC, ktbyers commented
Okay, CI-CD issues fixed. Now I can review/check this.

2023-04-17 03:02 UTC, ktbyers commented
@codekuu Did you run the Netmiko config and show tests against your code?

If so, can you post the output of your testing into the PR.

https://github.com/ktbyers/netmiko/blob/develop/TESTING.md

Thanks.

2023-04-17 17:11 UTC, ktbyers requested changes

2023-04-17 17:11 UTC, ktbyers commented on netmiko/ericsson/ericsson_mltn.py
> +        )
See comments below about save_config and commit methods.

2023-04-17 19:22 UTC, ktbyers commented
Also is there any paging of output i.e. --more-- (and a way to disable this behavior)?

2023-04-18 12:04 UTC, codekuu commented on netmiko/ericsson/ericsson_mltn.py
> +        login_sleep_multiplier: int = 5,
The problem with Ericsson MLTN is that the user you ssh with is not the same user that you sign in with.
So the ssh connection will be OK with cli@ but another user when the login prompt comes up.

2023-04-18 13:17 UTC, codekuu commented
> Also is there any paging of output i.e. --more-- (and a way to disable this behavior)?
@ktbyers 

No there is nothing like that, and I am not able to get the testing suite running correctly.
Having issues when running the py.test...
```
/netmiko/tests$ py.test -v tests/test_netmiko_show.py --test_device ericsson_mltn66
ImportError while loading conftest '/netmiko/tests/conftest.py'.
conftest.py:8: in <module>
    from netmiko import ConnectHandler, FileTransfer, InLineTransfer, SSHDetect
E   ModuleNotFoundError: No module named 'netmiko'
```
I do not have netmiko installed when running the tests.

However, I have tested this module for both Ericsson MLTN 66XX and 63XX series and works perfectly, both with salt and without salt.

2023-04-18 19:10 UTC, ktbyers commented on netmiko/ericsson/ericsson_mltn.py
> +        login_sleep_multiplier: int = 5,
Is the other user always `cli` or does that change?

2023-04-18 19:37 UTC, ktbyers commented
@codekuu I will see if I can help with your testing issue, but might be tonight or tomorrow.

2023-04-19 06:33 UTC, codekuu commented on netmiko/ericsson/ericsson_mltn.py
> +        login_sleep_multiplier: int = 5,
As of my understanding it is default and not changeable so yes, it is always `cli`.
So I removed the `default_ssh_username` part from the code and hardcoded it.

2023-04-19 06:33 UTC, codekuu commented
> @codekuu I will see if I can help with your testing issue, but might be tonight or tomorrow.

Awesome, thank you!

2023-04-19 17:28 UTC, ktbyers commented
@codekuu Okay, here is the process for setting up the Netmiko environment:

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#installing-netmiko-develop-branch-with-poetry-support

You will need to change your branch to your `ericsson-mltn-support` branch, but the rest of the process should be essentially the same.

Let me know if you run into any issues.

2023-04-20 15:12 UTC, codekuu commented
Weird that the mypy linting fails, works for me locally:
```
codekuu:/netmiko/netmiko/ericsson$ mypy --version
mypy 1.0.0 (compiled: yes)

codekuu:/netmiko/netmiko/ericsson$ mypy .
Success: no issues found in 3 source files
```

2023-04-20 18:10 UTC, codekuu commented
Thanks, totally missed the mypy configuration. Everything is now in the green.

2023-05-03 23:03 UTC, ktbyers commented
Superseded by:

https://github.com/ktbyers/netmiko/pull/3189

2023-05-03 23:03 UTC, closed without merging