Update extreme_ers_ssh.py
ktbyers/netmiko pull request #3258
Opened 2023-07-25 12:18 UTC by shivaraj-arch

Few Avaya ERS devices after SSH-login the Ctrl-Y turns to blank screen giving no pattern to search; prompt appears after Enter/Return key press ( tested ). With others this is just a Return key press and is safe.

Target Error: ReadTimeout::
Pattern not detected: '(?:sername|ssword|Ctrl-Y|(?m:[>#]\\s*$))' in output.

2023-10-20 04:11 UTC, shivaraj-arch reviewed
require approval from maintainer

2023-10-20 10:40 UTC, shivaraj-arch commented
[![Netmiko](https://github.com/shivaraj-arch/netmiko/actions/workflows/commit.yaml/badge.svg)](https://github.com/shivaraj-arch/netmiko/actions/workflows/commit.yaml)

2023-10-20 21:50 UTC, ktbyers commented
@shivaraj-arch Can you show me what the SSH login looks like on these Avaya ERS devices?

I.E. copy-and-paste the CLI interaction into this Github issue.

2023-10-20 21:51 UTC, ktbyers commented on .github/workflows/python-app.yml
> +        pytest
You should remove this (i.e. this change shouldn't be included in the PR).

2023-10-20 21:52 UTC, ktbyers requested changes
You should remove the GitHub actions file, that shouldn't be included in this PR.

2023-10-21 02:55 UTC, shivaraj-arch commented
> @shivaraj-arch Can you show me what the SSH login looks like on these Avaya ERS devices?
> 
> I.E. copy-and-paste the CLI interaction into this Github issue.

@ktbyers sorry do not have access to it now, just saw this still lying and hence tried running workflow. Have tested it thoroughly then. It won't affect existing functionality, so no harm in adopting changes.

2023-10-21 02:55 UTC, shivaraj-arch commented
> You should remove the GitHub actions file, that shouldn't be included in this PR.

Done.

2023-10-23 16:24 UTC, ktbyers approved these changes

2023-10-23 16:27 UTC, ktbyers commented
Superseded by:

https://github.com/ktbyers/netmiko/pull/3324

To fix merge/out-of-date issues.

2023-10-23 16:27 UTC, closed without merging